source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# sqlite3
gem "sqlite3", ">= 2.1"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

gem "thruster", require: false

gem "buda"
gem "fintoc"
gem "fintual"

gem "pagy"
gem "cryptocompare"
gem "data_migrate"
gem "draper"
gem "enumerize"
gem "money-rails"
gem "nokogiri"
gem "paper_trail"
gem "responders"
gem "jsonapi-serializer"

gem "power-types"
gem "pundit"
gem "rack-cors"
gem "rails-i18n"
gem "sidekiq"
gem "sidekiq-scheduler"

group :development do
  gem "annotaterb"
  gem "listen"
  gem "spring"
end

group :production do
  gem "rack-timeout"
  gem "rails_stdout_logging"
end

gem "dotenv", "~> 2.7", groups: [ :development, :production, :test ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "guard-rspec", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  gem "better_errors"
  gem "binding_of_caller"
  gem "pry-byebug"
  gem "pry-rails"
end
